export enum QueryKeyEnum {
  AUTH = "AUTH",
  USER = "USER",
  GET_USER_PROFILE = "GET_USER_PROFILE",
  ME = "ME",
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_POSTS = "GET_POSTS",
  GET_POST_DETAIL = "GET_POST_DETAIL",
  GET_POSTS_BY_CATEGORY = "GET_POSTS_BY_CATEGORY",
  GET_PERMISSIONS = "GET_PERMISSIONS",
  GET_USERS = "GET_USERS",
  GET_USER_DETAIL = "GET_USER_DETAIL",
  GET_TOP_POSTS = "GET_TOP_POSTS",
}
