export enum QueryKeyEnum {
  AUTH = "AUTH",
  USER = "USER",
  GET_USER_PROFILE = "GET_USER_PROFILE",
  ME = "ME",
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_POSTS = "GET_POSTS",
  GET_POST_DETAIL = "GET_POST_DETAIL",
  GET_POSTS_BY_CATEGORY = "GET_POSTS_BY_CATEGORY",
}
