export interface TranscriptSegment {
  id: number;
  start: number;
  duration: number;
  end: number;
  text: string;
  translation?: string;
}

export interface TranscriptLanguage {
  code: string;
  name: string;
  isAutoGenerated?: boolean;
}

export interface TranscriptResponse {
  videoId: string;
  language: string;
  availableLanguages: TranscriptLanguage[];
  segments: TranscriptSegment[];
}

export interface TranscriptErrorResponse {
  error: string;
}
